"""
Symphony Optimization - Model Registry + Adapter Pattern
Generated by Symphony AI with DeepSeek-R1
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, Any, List, Set, Optional
from enum import Enum

class ModelCapability(Enum):
    TEXT_GENERATION = "text_generation"
    IMAGE_CLASSIFICATION = "image_classification"
    SENTIMENT_ANALYSIS = "sentiment_analysis"
    TRANSLATION = "translation"
    SUMMARIZATION = "summarization"
    VISION = "vision"
    REASONING = "reasoning"
    IMAGE_GENERATION = "image_generation"
    VIDEO_GENERATION = "video_generation"
    EMBEDDING = "embedding"

class AdapterError(Exception):
    """Base exception for adapter-related errors"""

class ModelSelectionError(Exception):
    """Exception raised when no suitable model is found"""

class CapabilityMismatchError(Exception):
    """Exception raised when model capabilities don't match requirements"""

@dataclass
class ModelMetadata:
    id: str
    capabilities: Set[ModelCapability]
    description: str = ""
    version: str = "1.0"

class InputAdapter(ABC):
    @abstractmethod
    def adapt_input(self, data: Any, context: Optional[Dict[str, Any]] = None):
        """Convert raw input to model-specific input format"""
        pass

class OutputAdapter(ABC):
    @abstractmethod
    def adapt_output(self, model_output: Any, context: Optional[Dict[str, Any]] = None):
        """Convert model output to standardized format"""
        pass

class TextInputAdapter(InputAdapter):
    def adapt_input(self, data: Any, context: Optional[Dict[str, Any]] = None):
        return {"type": "text", "content": str(data)}

class VisionInputAdapter(InputAdapter):
    def adapt_input(self, data: Any, context: Optional[Dict[str, Any]] = None):
        return {"type": "image", "url": data}

class TextOutputAdapter(OutputAdapter):
    def adapt_output(self, model_output: Any, context: Optional[Dict[str, Any]] = None):
        return {"type": "text", "content": model_output}

class JsonOutputAdapter(OutputAdapter):
    def adapt_output(self, model_output: Any, context: Optional[Dict[str, Any]] = None):
        return {"type": "json", "data": model_output}

@dataclass
class ModelInfo:
    model_id: str
    provider: str
    capabilities: Set[ModelCapability]
    priority: int = 0
    enabled: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)

class ModelRegistry:
    """Centralized model management with capability registry"""
    
    def __init__(self):
        self._models: Dict[str, ModelInfo] = {}
        self._capability_index: Dict[ModelCapability, List[str]] = {}
    
    def register(self, model: ModelInfo):
        self._models[model.model_id] = model
        for cap in model.capabilities:
            if cap not in self._capability_index:
                self._capability_index[cap] = []
            self._capability_index[cap].append(model.model_id)
    
    def get(self, model_id: str) -> Optional[ModelInfo]:
        return self._models.get(model_id)
    
    def find_by_capability(self, capability: ModelCapability) -> List[ModelInfo]:
        model_ids = self._capability_index.get(capability, [])
        return [self._models[mid] for mid in model_ids if self._models[mid].enabled]
    
    def list_all(self) -> List[ModelInfo]:
        return list(self._models.values())

@dataclass
class CollaborationContext:
    """Shared context object for multi-model collaboration"""
    task_id: str = ""
    data: Dict[str, Any] = field(default_factory=dict)
    state: Dict[str, Any] = field(default_factory=dict)
    history: List[Dict[str, Any]] = field(default_factory=list)
    
    def update(self, key: str, value: Any):
        self.data[key] = value
        self.history.append({"action": "update", "key": key, "value": value})
    
    def get(self, key: str, default: Any = None) -> Any:
        return self.data.get(key, default)
