"""
Symphony Optimization - Config Manager + Logger + Monitor
Generated by Symphony AI with DeepSeek-V3.2
"""
import os
import json
import yaml
import time
import threading
from datetime import datetime
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, Optional, Union, List
from enum import Enum
from pathlib import Path
from collections import defaultdict, deque

class LogLevel(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class MetricType(str, Enum):
    LATENCY = "latency"
    THROUGHPUT = "throughput"
    ERROR_RATE = "error_rate"
    TOKEN_COUNT = "token_count"

@dataclass
class LogEntry:
    """Structured log entry"""
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    level: LogLevel = LogLevel.INFO
    message: str = ""
    module: str = ""
    correlation_id: str = ""
    extra: Dict[str, Any] = field(default_factory=dict)

@dataclass
class PerformanceMetric:
    """Performance metric data"""
    name: str
    value: float
    metric_type: MetricType
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    tags: Dict[str, str] = field(default_factory=dict)

class ConfigManager:
    """Centralized configuration management"""
    
    _instance = None
    _lock = threading.Lock()
    
    def __new__(cls):
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance
    
    def __init__(self):
        if self._initialized:
            return
        self._config: Dict[str, Any] = {}
        self._env_overrides: Dict[str, str] = {}
        self._initialized = True
    
    def load_from_file(self, path: str):
        """Load configuration from YAML/JSON file"""
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(f"Config file not found: {path}")
        
        with open(p, 'r') as f:
            if p.suffix in ['.yaml', '.yml']:
                self._config = yaml.safe_load(f) or {}
            elif p.suffix == '.json':
                self._config = json.load(f)
            else:
                raise ValueError(f"Unsupported config format: {p.suffix}")
        
        self._apply_env_overrides()
    
    def _apply_env_overrides(self):
        """Apply environment variable overrides"""
        for key, value in os.environ.items():
            if key.startswith('SYMPHONY_'):
                config_key = key[9:].lower()
                self._config[config_key] = value
    
    def get(self, key: str, default: Any = None) -> Any:
        """Get configuration value"""
        keys = key.split('.')
        value = self._config
        for k in keys:
            if isinstance(value, dict):
                value = value.get(k)
            else:
                return default
            if value is None:
                return default
        return value
    
    def set(self, key: str, value: Any):
        """Set configuration value"""
        keys = key.split('.')
        target = self._config
        for k in keys[:-1]:
            if k not in target:
                target[k] = {}
            target = target[k]
        target[keys[-1]] = value

class StructuredLogger:
    """Structured logging with JSON format"""
    
    def __init__(self, name: str = "symphony", level: LogLevel = LogLevel.INFO):
        self.name = name
        self.level = level
        self._logs: List[LogEntry] = []
        self._lock = threading.Lock()
    
    def _log(self, level: LogLevel, message: str, **extra):
        entry = LogEntry(
            level=level,
            message=message,
            module=self.name,
            extra=extra
        )
        with self._lock:
            self._logs.append(entry)
        print(json.dumps(asdict(entry), ensure_ascii=False))
    
    def debug(self, message: str, **extra):
        self._log(LogLevel.DEBUG, message, **extra)
    
    def info(self, message: str, **extra):
        self._log(LogLevel.INFO, message, **extra)
    
    def warning(self, message: str, **extra):
        self._log(LogLevel.WARNING, message, **extra)
    
    def error(self, message: str, **extra):
        self._log(LogLevel.ERROR, message, **extra)

class PerformanceMonitor:
    """Real-time performance monitoring"""
    
    def __init__(self, max_history: int = 1000):
        self.max_history = max_history
        self._metrics: Dict[str, deque] = defaultdict(lambda: deque(maxlen=max_history))
        self._lock = threading.Lock()
    
    def record(self, name: str, value: float, metric_type: MetricType = MetricType.LATENCY, **tags):
        metric = PerformanceMetric(
            name=name,
            value=value,
            metric_type=metric_type,
            tags=tags
        )
        with self._lock:
            self._metrics[name].append(metric)
    
    def get_stats(self, name: str) -> Dict[str, float]:
        """Get statistics for a metric"""
        with self._lock:
            values = [m.value for m in self._metrics.get(name, [])]
            if not values:
                return {}
            return {
                "count": len(values),
                "sum": sum(values),
                "avg": sum(values) / len(values),
                "min": min(values),
                "max": max(values)
            }
    
    def get_recent(self, name: str, n: int = 10) -> List[PerformanceMetric]:
        """Get recent metrics"""
        with self._lock:
            return list(self._metrics.get(name, []))[-n:]
