"""
Symphony Optimization - Error Handling + Fallback
Generated by Symphony AI with DeepSeek-R1
"""
import logging
import time
import random
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Callable, List, Optional, TypeVar, Any, Dict

# Error codes (1000-9999 range)
class ErrorCode(IntEnum):
    UNKNOWN_ERROR = 1000
    NETWORK_ERROR = 1001
    TIMEOUT_ERROR = 1002
    MODEL_FAILURE = 1003
    FALLBACK_EXHAUSTED = 1004
    INVALID_INPUT = 1005
    RATE_LIMIT = 1305

class SymphonyError(Exception):
    """Base exception class with structured error codes"""
    def __init__(
        self,
        code: ErrorCode,
        message: str = "An error occurred",
        details: Optional[Dict[str, Any]] = None
    ):
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}

    def __str__(self):
        return f"[{self.code.name}] {self.message}"

R = TypeVar("R")

@dataclass
class ErrorHandler:
    """Centralized error handling with retry logic"""
    max_retries: int = 3
    backoff_factor: float = 0.3
    jitter: float = 0.1
    logger: logging.Logger = field(default_factory=lambda: logging.getLogger(__name__))
    
    def calculate_delay(self, attempt: int) -> float:
        delay = self.backoff_factor * (2 ** attempt)
        jitter = delay * self.jitter * random.random()
        return delay + jitter
    
    def execute_with_retry(
        self,
        func: Callable[..., R],
        *args,
        **kwargs
    ) -> R:
        last_exception = None
        for attempt in range(self.max_retries + 1):
            try:
                return func(*args, **kwargs)
            except SymphonyError as e:
                last_exception = e
                if e.code == ErrorCode.RATE_LIMIT:
                    self.logger.warning(f"Rate limited, attempt {attempt + 1}/{self.max_retries + 1}")
                elif attempt < self.max_retries:
                    delay = self.calculate_delay(attempt)
                    self.logger.info(f"Retrying in {delay:.2f}s...")
                    time.sleep(delay)
                else:
                    self.logger.error(f"All retries exhausted: {e}")
                    raise
            except Exception as e:
                last_exception = e
                if attempt < self.max_retries:
                    delay = self.calculate_delay(attempt)
                    time.sleep(delay)
                else:
                    raise
        raise last_exception

@dataclass
class FallbackModel:
    """Fallback model configuration"""
    model_id: str
    priority: int = 0
    max_retries: int = 2

class FallbackManager:
    """Model chain execution with fallback support"""
    
    def __init__(self, error_handler: Optional[ErrorHandler] = None):
        self.error_handler = error_handler or ErrorHandler()
        self.fallback_chains: Dict[str, List[FallbackModel]] = {}
        self.logger = self.error_handler.logger
    
    def register_chain(self, primary_model: str, fallbacks: List[FallbackModel]):
        """Register a fallback chain for a primary model"""
        self.fallback_chains[primary_model] = sorted(fallbacks, key=lambda x: x.priority)
    
    def execute_with_fallback(
        self,
        primary_model: str,
        func: Callable[..., R],
        *args,
        **kwargs
    ) -> R:
        """Execute function with fallback models"""
        chain = [FallbackModel(primary_model, priority=0)]
        chain.extend(self.fallback_chains.get(primary_model, []))
        
        last_error = None
        for fb_model in chain:
            try:
                self.logger.info(f"Trying model: {fb_model.model_id}")
                return func(*args, model_id=fb_model.model_id, **kwargs)
            except SymphonyError as e:
                last_error = e
                self.logger.warning(f"Model {fb_model.model_id} failed: {e}")
                continue
            except Exception as e:
                last_error = e
                self.logger.warning(f"Model {fb_model.model_id} error: {e}")
                continue
        
        raise SymphonyError(
            ErrorCode.FALLBACK_EXHAUSTED,
            f"All models in chain failed. Last error: {last_error}"
        )
